name: go

concurrency:
  group: ${{ github.workflow }}/${{ github.ref_name }}

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
      - "vendor/**"
      - ".traefik.yml"
      - ".github/workflows/go.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
      - "vendor/**"
      - ".traefik.yml"
      - ".github/workflows/go.yml"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Run linter
        run: go vet ./...

      - name: Check vendoring
        run: |
          go mod vendor
          git add .
          git diff --staged --exit-code

      - name: Run tests
        run: go test -race ./...
